image:
  repository: real-estate-agent
  tag: latest
  pullPolicy: IfNotPresent

redis:
  enabled: true
  image: redis:7
  resources:
    limits:
      cpu: 200m
      memory: 256Mi

api:
  port: 8001
  replicaCount: 1
  resources:
    limits:
      cpu: 300m
      memory: 512Mi
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70

scraper:
  pages: 3
  schedule: "0 * * * *"
  resources:
    limits:
      cpu: 200m
      memory: 256Mi

worker:
  replicaCount: 1
  resources:
    limits:
      cpu: 300m
      memory: 512Mi

ingress:
  enabled: true
  host: real-estate.local
  tlsSecret: real-estate-tls
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
