apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "{{ .Values.api.port }}"]
          ports:
            - containerPort: {{ .Values.api.port }}
          env:
            - name: REDIS_URL
              value: "redis://redis:6379/0"
            - name: GEMINI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: GEMINI_API_KEY
