name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
          pip install flake8
          pip install coverage
      - name: Lint
        run: flake8 back_end api
      - name: Generate Features
        run: python back_end/prepare_features.py
      - name: Feast apply
        run: feast apply -f feature_repo
      - name: Feast materialize
        run: feast materialize-incremental $(date +"%Y-%m-%dT%H:%M:%S") -f feature_repo
      - name: Build Docker image
        run: docker build -t real-estate-agent:latest .
      - name: Trivy vulnerability scan
        uses: aquasecurity/trivy-action@0.13.1
        with:
          image-ref: real-estate-agent:latest
          severity: CRITICAL,HIGH
          ignore-unfixed: true
      - name: Build docs
        run: |
          pip install mkdocs-material
          mkdocs build --strict
      - name: Run pre-commit
        run: |
          pip install pre-commit
          pre-commit run --all-files --show-diff-on-failure
      - name: Run tests with coverage
        run: |
          coverage run -m pytest
          coverage xml -o coverage.xml
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage.xml
      - name: Generate SBOM
        run: |
          pip install cyclonedx-bom
          cyclonedx-py --output-file sbom.xml
      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.xml
      - name: Run tests
        run: pytest -q
